// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAgency.Data;

#nullable disable

namespace TravelAgency.Data.Migrations
{
    [DbContext(typeof(TravelAgencyDbContext))]
    [Migration("20230728201343_Order")]
    partial class Order
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            PhoneNumber = "+359888888888",
                            UserId = new Guid("dea12856-c198-4129-b3f3-b893d8395082")
                        });
                });

            modelBuilder.Entity("TravelAgency.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dea12856-c198-4129-b3f3-b893d8395082"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8149bb4-1858-4d61-83a3-fcd207b9dd40",
                            Email = "agent@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "agent@mail.com",
                            NormalizedUserName = "agent@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEFWU8gn3sRFn85ZJdg9dKJtwk7oiC6Sk5KW2clf9CCum9ywnaqSzA7j/BqPpnzpsdQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "075a14a0-0980-4d51-8566-8232f13ee9ee",
                            TwoFactorEnabled = false,
                            UserName = "agent@mail.com"
                        },
                        new
                        {
                            Id = new Guid("6d5800ce-d726-4fc8-83d9-d6b3ac1f591e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "786dc529-d9d1-49dd-9a53-096c06874753",
                            Email = "guest@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "guest@mail.com",
                            NormalizedUserName = "guest@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEDV7SGbq07FjAtVzFhJO+A8Y3ueU9/cd1rcFci0g31sJkniL+Xuq+8XgZYZ8WjtVqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dd7264c-3628-4395-803a-6faa5bf86353",
                            TwoFactorEnabled = false,
                            UserName = "guest@mail.com"
                        });
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Семеен хотел"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Хотел"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Апартхотел"
                        });
                });

            modelBuilder.Entity("TravelAgency.Data.Models.CateringType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CateringTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RoomOnly"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BedAndBreakfast"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HalfBoard"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FullBoard"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AllInclusive"
                        });
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApartmentRoomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CateringTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DoubleRoomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<decimal>("StudioRoomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CateringTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            ApartmentRoomPrice = 0m,
                            CategoryId = 1,
                            CateringTypeId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Хотел в новата част на Созопол. Намира се събсем близо до плажа.",
                            DoubleRoomPrice = 100m,
                            IsActive = true,
                            LocationId = 1,
                            Star = 4,
                            StudioRoomPrice = 0m,
                            Title = "ЛАГУНА БИЙЧ"
                        },
                        new
                        {
                            Id = 2,
                            AgentId = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            ApartmentRoomPrice = 0m,
                            CategoryId = 1,
                            CateringTypeId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Хотел „Табанов бийч” е разположен в новата част на град Созопол. Намира се само на 60м. от плаж \"Хармани\", а в близост има много магазини, ресторанти, клубове и други развлечения..",
                            DoubleRoomPrice = 120m,
                            IsActive = true,
                            LocationId = 1,
                            Star = 3,
                            StudioRoomPrice = 0m,
                            Title = "ТАБАНОВ БИЙЧ"
                        },
                        new
                        {
                            Id = 3,
                            AgentId = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            ApartmentRoomPrice = 0m,
                            CategoryId = 2,
                            CateringTypeId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Хотел „Аполис” се намира на много тихо и спокойно място в новата част на града. Разположен е на 70 м от плаж Хармани. Той е уютен и луксозен хотел, с интересна архитектура.",
                            DoubleRoomPrice = 120m,
                            IsActive = true,
                            LocationId = 1,
                            Star = 3,
                            StudioRoomPrice = 0m,
                            Title = "АПОЛИС"
                        },
                        new
                        {
                            Id = 4,
                            AgentId = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            ApartmentRoomPrice = 0m,
                            CategoryId = 2,
                            CateringTypeId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Аполония Резорт е изискан четиризвезден ваканционен комплекс от затворен тип, разположен на един от най- красивите плажове по българското черноморие - великолепния Царския плаж. Царският плаж е разположен между курортите Черноморец на север и Созопол на юг.",
                            DoubleRoomPrice = 120m,
                            IsActive = true,
                            LocationId = 2,
                            Star = 4,
                            StudioRoomPrice = 0m,
                            Title = "АПОЛОНИЯ РЕЗОРТ"
                        },
                        new
                        {
                            Id = 5,
                            AgentId = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            ApartmentRoomPrice = 0m,
                            CategoryId = 3,
                            CateringTypeId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Хотел „Аркутино Фемили Ризорт “ се намира на южното Черноморие на 40 км от град Бургас, между Созопол и Приморско в местността Аркутино, която е част от резервата „Ропотамо“. Разположен е в непосредствена близост до един от най-красивите български плажове, между златисти пясъчни дюни, прочутото крайморско езеро Водните лилии и река Ропотамо.",
                            DoubleRoomPrice = 170m,
                            IsActive = true,
                            LocationId = 3,
                            Star = 4,
                            StudioRoomPrice = 0m,
                            Title = "АРКУТИНО ФЕМИЛИ РЕЗОРТ"
                        },
                        new
                        {
                            Id = 6,
                            AgentId = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            ApartmentRoomPrice = 0m,
                            CategoryId = 3,
                            CateringTypeId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Аполония резорт е луксозен, апартаментен комплекс от затворен тип, състоящ се от две четири етажни сгради с капацитет от 23 апартамента. Апартаментите са от различен тип, напълно оборудвани с всичко необходимо за престоя на своите гости. Намира се в района на живописното черноморско градче Черноморец, на 400 м от центъра и на 300 м от златистия плаж. Хотелът разполага със собствен ресторант, където гостите ползват отстъпка.",
                            DoubleRoomPrice = 200m,
                            IsActive = true,
                            LocationId = 2,
                            Star = 4,
                            StudioRoomPrice = 0m,
                            Title = "АТИЯ РЕЗОРТ"
                        },
                        new
                        {
                            Id = 7,
                            AgentId = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            ApartmentRoomPrice = 0m,
                            CategoryId = 1,
                            CateringTypeId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Къща за гости Дари се намира в новата част на античния град Созопол. Тя е разположена между два плажа на разстояние 5 - 6 минути от всеки плаж. Къщата се намира на тиха и спокойна улица, която дава възможност на туристите за пълноценна почивка. Къщата за гости разполага със самостоятелни стаи и апартаменти. Всички помещения са с тераса, санитарен възел, телевизор, хладилник, климатик и безплатен интернет.",
                            DoubleRoomPrice = 100m,
                            IsActive = true,
                            LocationId = 1,
                            Star = 3,
                            StudioRoomPrice = 0m,
                            Title = "ВИЛА ДАРИ"
                        },
                        new
                        {
                            Id = 8,
                            AgentId = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            ApartmentRoomPrice = 0m,
                            CategoryId = 1,
                            CateringTypeId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Разположен върху живописни скали на морския бряг в новата част на града, хотел „Фиорд” е идеален за мечтаната почивка. Плаж „Хармани” се намира на 60м. Хотелът разполага с еднакво обзаведени Двойни стаи от различен тип, различаващи се по площта си.",
                            DoubleRoomPrice = 160m,
                            IsActive = true,
                            LocationId = 1,
                            Star = 3,
                            StudioRoomPrice = 0m,
                            Title = "ХОРИЗОНТ"
                        },
                        new
                        {
                            Id = 9,
                            AgentId = new Guid("0174683e-a3fd-4f3c-a2b7-3c3792dad867"),
                            ApartmentRoomPrice = 0m,
                            CategoryId = 1,
                            CateringTypeId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Разположен върху живописни скали на морския бряг в новата част на града, хотел „Фиорд” е идеален за мечтаната почивка. Плаж „Хармани” се намира на 60м. Хотелът разполага с еднакво обзаведени Двойни стаи от различен тип, различаващи се по площта си.",
                            DoubleRoomPrice = 130m,
                            IsActive = true,
                            LocationId = 1,
                            Star = 3,
                            StudioRoomPrice = 0m,
                            Title = "ФИОРД"
                        });
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            HotelId = 1,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/149/big/IMG_4383.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 6,
                            HotelId = 1,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/149/big/IMG_4543.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 7,
                            HotelId = 1,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/149/big/CRW_4025.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 8,
                            HotelId = 1,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/149/big/CRW_4026.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 9,
                            HotelId = 1,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/149/big/CRW_4033.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 10,
                            HotelId = 2,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/8/big/RXES.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 11,
                            HotelId = 2,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/8/big/DSC_0686.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 12,
                            HotelId = 2,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/8/big/DSC_0676.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 13,
                            HotelId = 2,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/8/big/DSC_0672.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 14,
                            HotelId = 2,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/8/big/DSC_0685.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 15,
                            HotelId = 3,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/7/big/B7NF.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 16,
                            HotelId = 3,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/7/big/Z4Y7.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 17,
                            HotelId = 3,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/7/big/DSC_0114.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 18,
                            HotelId = 3,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/7/big/DSC_0115.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 19,
                            HotelId = 3,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/7/big/58MB.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 20,
                            HotelId = 4,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel///136/big/P1000721.JPG",
                            IsMain = true
                        },
                        new
                        {
                            Id = 21,
                            HotelId = 4,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel///136/big/P1000761.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 22,
                            HotelId = 4,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel///136/big/P1000760.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 23,
                            HotelId = 4,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel///136/big/P1000736.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 24,
                            HotelId = 4,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel///136/big/P1000718.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 25,
                            HotelId = 5,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG//67/big/DSC_0826.JPG",
                            IsMain = true
                        },
                        new
                        {
                            Id = 26,
                            HotelId = 5,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG//67/big/P8270161.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 27,
                            HotelId = 5,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG//67/big/P8270157.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 28,
                            HotelId = 5,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG//67/big/DSC_0883.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 29,
                            HotelId = 5,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG//67/big/DSC_0882.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 30,
                            HotelId = 6,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8142/130/big/1.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 31,
                            HotelId = 6,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8142/130/big/_MG_7398.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 32,
                            HotelId = 6,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8142/130/big/_MG_7250.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 33,
                            HotelId = 6,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8142/130/big/_MG_7275.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 34,
                            HotelId = 6,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8142/130/big/3.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 35,
                            HotelId = 7,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/155/big/New%20Image.JPG",
                            IsMain = true
                        },
                        new
                        {
                            Id = 36,
                            HotelId = 7,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/155/big/DARI-2%20izgled.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 37,
                            HotelId = 7,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/155/big/DARI-staya.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 38,
                            HotelId = 7,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/155/big/DARI-%20NOMER%202.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 39,
                            HotelId = 7,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/155/big/DARI-%20NOMER%202.2.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 40,
                            HotelId = 8,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/33/big/CRW_4068.jpg",
                            IsMain = true
                        },
                        new
                        {
                            Id = 41,
                            HotelId = 8,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/33/big/150815_289__MG_5112.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 42,
                            HotelId = 8,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/33/big/150815_289__MG_5038-HDR.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 43,
                            HotelId = 8,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/33/big/IMG_4450.JPGg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 44,
                            HotelId = 8,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/33/big/IMG_4495.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 45,
                            HotelId = 9,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/15/big/DSC_0063.JPG",
                            IsMain = true
                        },
                        new
                        {
                            Id = 46,
                            HotelId = 9,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/15/big/Hotel%20Fjord%20B1_6.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 47,
                            HotelId = 9,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/15/big/DSC_0063.JPG",
                            IsMain = false
                        },
                        new
                        {
                            Id = 48,
                            HotelId = 9,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/15/big/Hotel%20Fjord%20A_1.jpg",
                            IsMain = false
                        },
                        new
                        {
                            Id = 49,
                            HotelId = 9,
                            ImageUrl = "https://store.crs.bg/seastar-2016/img_hotel/BG/8130/15/big/Hotel%20Fjord%20Sozopol%20breakfast-7.JPG",
                            IsMain = false
                        });
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Созопол"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Черноморец"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Дюни"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Слънчев бряг"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Златни пясъци"
                        });
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("АccommodationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderLists");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Прекрасно преживяване в хотела! Уютна стая, отлично обслужване и изискан ресторант. Няма как да не се чувстваш приветливо посрещнат и релаксиран. Препоръчвам",
                            HotelId = 1,
                            UserId = new Guid("6d5800ce-d726-4fc8-83d9-d6b3ac1f591e")
                        },
                        new
                        {
                            Id = 2,
                            Content = "Къщата за гости беше просто превъзходна! Прекарахме незабравим уикенд сред природата, в компанията на любезни домакини. Всичко беше перфектно - от удобствата до гледката. С удоволствие ще се върнем отново!",
                            HotelId = 2,
                            UserId = new Guid("6d5800ce-d726-4fc8-83d9-d6b3ac1f591e")
                        },
                        new
                        {
                            Id = 3,
                            Content = "Невероятно преживяване в този хотел. Спокойствие, лукс и безупречно обслужване. От момента на пристигането до заминаването си се чувствахме като VIP гости. Благодарим на персонала за прекрасния престой!",
                            HotelId = 3,
                            UserId = new Guid("6d5800ce-d726-4fc8-83d9-d6b3ac1f591e")
                        },
                        new
                        {
                            Id = 4,
                            Content = "Хотелът ни очарова с уникален дизайн и стил. Всяка детайлна измислица беше внимателно изпълнена. Спяхме в комфортен легловия аранжимент и се насладихме на изисканата храна. Подгответе се за неповторимо изживяване!",
                            HotelId = 4,
                            UserId = new Guid("6d5800ce-d726-4fc8-83d9-d6b3ac1f591e")
                        },
                        new
                        {
                            Id = 5,
                            Content = "Къщата за гости беше уютна и пълна със сърце и душа. Гостоприемните домакини ни посрещнаха с топлина и готвената храна беше вкусна и автентична. Проведохме спокоен и релаксиращ уикенд в прекрасна обстановка.",
                            HotelId = 5,
                            UserId = new Guid("6d5800ce-d726-4fc8-83d9-d6b3ac1f591e")
                        },
                        new
                        {
                            Id = 6,
                            Content = "Семейният ни престой в този хотел беше мечтан. Басейнът и игралната зала развълнуваха децата, докато спа-центърът ни предложи наистина релаксиращ опит. Отлична комбинация от забавление и отдих!",
                            HotelId = 6,
                            UserId = new Guid("dea12856-c198-4129-b3f3-b893d8395082")
                        },
                        new
                        {
                            Id = 7,
                            Content = "Избрахме тази къща за гости за нашата романтична почивка и не бихме могли да бъдем по-щастливи. Атмосферата беше магична, а гледката от терасата буквално откъсна дъха. Ще я препоръчаме на всички!",
                            HotelId = 1,
                            UserId = new Guid("dea12856-c198-4129-b3f3-b893d8395082")
                        },
                        new
                        {
                            Id = 8,
                            Content = "Хотелът беше прекрасно решение за нашия семеен отдих. Паркът и детските площадки зарадваха децата, а ресторантът ни предложи невероятни вкусове. Прекарахме незабравимо време с любимите си хора.",
                            HotelId = 2,
                            UserId = new Guid("dea12856-c198-4129-b3f3-b893d8395082")
                        },
                        new
                        {
                            Id = 9,
                            Content = "Невероятна къща за гости, вложена със стил и комфорт. Пълноценното оборудване и уютната атмосфера ни позволиха да се отпуснем напълно. Прекарахме прекрасна почивка сред природата.",
                            HotelId = 3,
                            UserId = new Guid("dea12856-c198-4129-b3f3-b893d8395082")
                        });
                });

            modelBuilder.Entity("TravelAgency.Data.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Double room"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Studio"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Apartment"
                        });
                });

            modelBuilder.Entity("TravelAgency.Data.Models.WishList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgency.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Agent", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Hotel", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.Agent", "Agent")
                        .WithMany("OwnedHotel")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelAgency.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgency.Data.Models.CateringType", "CateringType")
                        .WithMany()
                        .HasForeignKey("CateringTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgency.Data.Models.Location", "Location")
                        .WithMany("HotelsInThisLocation")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("CateringType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Image", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.Hotel", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Order", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.Hotel", "Hotel")
                        .WithMany("OrderLists")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgency.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("MyOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Post", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.Hotel", "Hotel")
                        .WithMany("Posts")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgency.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("MyPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.RoomType", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.Hotel", null)
                        .WithMany("RoomTypes")
                        .HasForeignKey("HotelId");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.WishList", b =>
                {
                    b.HasOne("TravelAgency.Data.Models.Hotel", "Hotel")
                        .WithMany("WishLists")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgency.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("MyWishLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Agent", b =>
                {
                    b.Navigation("OwnedHotel");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("MyOrders");

                    b.Navigation("MyPosts");

                    b.Navigation("MyWishLists");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Hotel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderLists");

                    b.Navigation("Posts");

                    b.Navigation("RoomTypes");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("TravelAgency.Data.Models.Location", b =>
                {
                    b.Navigation("HotelsInThisLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
